// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrgChartEngines.Data;

#nullable disable

namespace OrgChartEngines.Migrations.Migrations_WeldContext
{
    [DbContext(typeof(Engines_PCContext))]
    partial class Weld_PCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.Departament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DepartamentName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departament", (string)null);
                });

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.Line", b =>
                {
                    b.Property<int>("line_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("line_id"), 1L, 1);

                    b.Property<string>("line_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("line_id");

                    b.ToTable("Line", (string)null);
                });

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.OrgChartPosition", b =>
                {
                    b.Property<int>("IdPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPosition"), 1L, 1);

                    b.Property<string>("Assemblies")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdDepartment")
                        .HasColumnType("int");

                    b.Property<int?>("IdLine")
                        .HasColumnType("int");

                    b.Property<int?>("IdLineSub")
                        .HasColumnType("int");

                    b.Property<string>("IdRol")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdUser")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("PositionLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SuperiorPosition")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPosition");

                    b.ToTable("OrgChart_Positions", (string)null);
                });

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.PositionUser", b =>
                {
                    b.Property<int>("IdPositionUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPositionUser"), 1L, 1);

                    b.Property<int?>("IdPosition")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("Shift")
                        .HasColumnType("int");

                    b.HasKey("IdPositionUser");

                    b.HasIndex("IdPosition");

                    b.ToTable("PositionUser", (string)null);
                });

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.RolesDepartment", b =>
                {
                    b.Property<int>("IdRolDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolDepartment"), 1L, 1);

                    b.Property<int>("IdDepartment")
                        .HasColumnType("int");

                    b.Property<string>("IdRol")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("IdRolDepartment");

                    b.HasIndex("IdDepartment");

                    b.ToTable("RolesDepartments");
                });

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.PositionUser", b =>
                {
                    b.HasOne("OrgChartWeld.Models.OrgChart.OrgChartPosition", "IdPositionNavigation")
                        .WithMany("PositionUsers")
                        .HasForeignKey("IdPosition")
                        .HasConstraintName("FK_PositionUser_OrgChart_Positions");

                    b.Navigation("IdPositionNavigation");
                });

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.RolesDepartment", b =>
                {
                    b.HasOne("OrgChartWeld.Models.OrgChart.Departament", "IdDepartmentNavigation")
                        .WithMany("RolesDepartments")
                        .HasForeignKey("IdDepartment")
                        .IsRequired()
                        .HasConstraintName("FK_RolesDepartments_Departament");

                    b.Navigation("IdDepartmentNavigation");
                });

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.Departament", b =>
                {
                    b.Navigation("RolesDepartments");
                });

            modelBuilder.Entity("OrgChartWeld.Models.OrgChart.OrgChartPosition", b =>
                {
                    b.Navigation("PositionUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
